# Generated by Django 3.1.5 on 2021-06-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('visited_day', models.CharField(blank=True, db_column='visited_day', max_length=50, null=True)),
                ('region', models.CharField(blank=True, db_column='region', max_length=50, null=True)),
                ('cafe_name', models.CharField(blank=True, db_column='cafe_name', max_length=50, null=True)),
                ('theme_name', models.CharField(blank=True, db_column='theme_name', max_length=50, null=True)),
                ('participant_num', models.IntegerField(blank=True, db_column='participant_num', default=2, null=True)),
                ('escape_flag', models.CharField(blank=True, db_column='escape_flag', default='O', max_length=1, null=True)),
                ('r_time', models.CharField(blank=True, db_column='r_time', max_length=50, null=True)),
                ('content', models.CharField(blank=True, db_column='content', max_length=300, null=True)),
                ('updt_dt', models.DateTimeField(auto_now=True, db_column='updt_dt')),
                ('insrt_dt', models.DateTimeField(auto_now_add=True, db_column='insrt_dt')),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='BBizarea',
        ),
        migrations.DeleteModel(
            name='BBizpartner',
        ),
        migrations.DeleteModel(
            name='BBizunit',
        ),
        migrations.DeleteModel(
            name='BCo',
        ),
        migrations.DeleteModel(
            name='BFactory',
        ),
        migrations.DeleteModel(
            name='BItem',
        ),
        migrations.DeleteModel(
            name='BItemaccnt',
        ),
        migrations.DeleteModel(
            name='BItemgrp',
        ),
        migrations.DeleteModel(
            name='BomDtl',
        ),
        migrations.DeleteModel(
            name='BomHdr',
        ),
        migrations.DeleteModel(
            name='BWorkcenter',
        ),
        migrations.DeleteModel(
            name='CbCodeDtl',
        ),
        migrations.DeleteModel(
            name='CbCodeHdr',
        ),
        migrations.DeleteModel(
            name='CbCostCenter',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
    ]
